from django.db import models

class galaxy(models.Model):
  
  
     
     image3=models.ImageField(upload_to="gal/images" , default="")
     image4=models.ImageField(upload_to="gal/images",default="")
     image5=models.ImageField(upload_to="gal/images" , default="")
     image6=models.ImageField(upload_to="gal/images",default="")
     image7=models.ImageField(upload_to="gal/images" , default="")
     image8=models.ImageField(upload_to="gal/images",default="")
     image9=models.ImageField(upload_to="gal/images" , default="")
     image10=models.ImageField(upload_to="gal/images",default="")
     image11=models.ImageField(upload_to="gal/images" , default="")
     text=models.CharField(max_length=122,default="")
     text2=models.CharField(max_length=122,default="")
     text3=models.CharField(max_length=122,default="")
     text4=models.CharField(max_length=122,default="")
     text5=models.CharField(max_length=122,default="")
     text6=models.CharField(max_length=122,default="")
     text7=models.CharField(max_length=122,default="")
     text8=models.CharField(max_length=122,default="")
     text9=models.CharField(max_length=122,default="")
     text10=models.CharField(max_length=122,default="")
     text11=models.CharField(max_length=122,default="")
     text12=models.CharField(max_length=122,default="")
     text13=models.CharField(max_length=122,default="")
     text14=models.CharField(max_length=122,default="")
     text15=models.CharField(max_length=122,default="")
     text16=models.CharField(max_length=122,default="")
     text17=models.CharField(max_length=122,default="")
     text18=models.CharField(max_length=122,default="")
     text19=models.CharField(max_length=122,default="")
     text20=models.CharField(max_length=122,default="")
     text21=models.CharField(max_length=122,default="")
     text22=models.CharField(max_length=122,default="")
     text23=models.CharField(max_length=122,default="")
     text24=models.CharField(max_length=122,default="")
     text25=models.CharField(max_length=122,default="")
     text26=models.CharField(max_length=122,default="")
     text27=models.CharField(max_length=122,default="")
     text28=models.CharField(max_length=122,default="")
     text29=models.CharField(max_length=122,default="")
     text30=models.CharField(max_length=122,default="")
     text31=models.CharField(max_length=122,default="")
     text32=models.CharField(max_length=122,default="")
     text33=models.CharField(max_length=122,default="")
     text34=models.CharField(max_length=122,default="")
     text35=models.CharField(max_length=122,default="")
     text36=models.CharField(max_length=122,default="")
     text37=models.CharField(max_length=122,default="")
     text38=models.CharField(max_length=122,default="")
     text39=models.CharField(max_length=122,default="")
     text40=models.CharField(max_length=122,default="")
     text41=models.CharField(max_length=122,default="")
     text42=models.CharField(max_length=122,default="")
     text43=models.CharField(max_length=122,default="")
     text44=models.CharField(max_length=122,default="")
     text45=models.CharField(max_length=122,default="")
    
     
     
     
class ma(models.Model):
     image3=models.ImageField(upload_to="gal/images" , default="")
     image4=models.ImageField(upload_to="gal/images",default="")
     image5=models.ImageField(upload_to="gal/images" , default="")
     image6=models.ImageField(upload_to="gal/images",default="")
     image7=models.ImageField(upload_to="gal/images" , default="")
     image8=models.ImageField(upload_to="gal/images",default="")
     image9=models.ImageField(upload_to="gal/images" , default="")
     image10=models.ImageField(upload_to="gal/images",default="")
     image11=models.ImageField(upload_to="gal/images" , default="")
     text=models.CharField(max_length=122,default="")
     text2=models.CharField(max_length=122,default="")
     text3=models.CharField(max_length=122,default="")
     text4=models.CharField(max_length=122,default="")
     text5=models.CharField(max_length=122,default="")
     text6=models.CharField(max_length=122,default="")
     text7=models.CharField(max_length=122,default="")
     text8=models.CharField(max_length=122,default="")
     text9=models.CharField(max_length=122,default="")
     text10=models.CharField(max_length=122,default="")
     text11=models.CharField(max_length=122,default="")
     text12=models.CharField(max_length=122,default="")
     text13=models.CharField(max_length=122,default="")
     text14=models.CharField(max_length=122,default="")
     text15=models.CharField(max_length=122,default="")
     text16=models.CharField(max_length=122,default="")
     text17=models.CharField(max_length=122,default="")
     text18=models.CharField(max_length=122,default="")
     text19=models.CharField(max_length=122,default="")
     text20=models.CharField(max_length=122,default="")
     text21=models.CharField(max_length=122,default="")
     text22=models.CharField(max_length=122,default="")
     text23=models.CharField(max_length=122,default="")
     text24=models.CharField(max_length=122,default="")
     text25=models.CharField(max_length=122,default="")
     text26=models.CharField(max_length=122,default="")
     text27=models.CharField(max_length=122,default="")
     text28=models.CharField(max_length=122,default="")
     text29=models.CharField(max_length=122,default="")
     text30=models.CharField(max_length=122,default="")
     text31=models.CharField(max_length=122,default="")
     text32=models.CharField(max_length=122,default="")
     text33=models.CharField(max_length=122,default="")
     text34=models.CharField(max_length=122,default="")
     text35=models.CharField(max_length=122,default="")
     text36=models.CharField(max_length=122,default="")
     text37=models.CharField(max_length=122,default="")
     text38=models.CharField(max_length=122,default="")
     text39=models.CharField(max_length=122,default="")
     text40=models.CharField(max_length=122,default="")
     text41=models.CharField(max_length=122,default="")
     text42=models.CharField(max_length=122,default="")
     text43=models.CharField(max_length=122,default="")
     text44=models.CharField(max_length=122,default="")
     text45=models.CharField(max_length=122,default="")
# Create your models here.
class rats(models.Model):
      
     image3=models.ImageField(upload_to="gal/images" , default="")
     image4=models.ImageField(upload_to="gal/images",default="")
     image5=models.ImageField(upload_to="gal/images" , default="")
     image6=models.ImageField(upload_to="gal/images",default="")
     image7=models.ImageField(upload_to="gal/images" , default="")
     image8=models.ImageField(upload_to="gal/images",default="")
     image9=models.ImageField(upload_to="gal/images" , default="")
     image10=models.ImageField(upload_to="gal/images",default="")
     image11=models.ImageField(upload_to="gal/images" , default="")
     text=models.CharField(max_length=122,default="")
     text2=models.CharField(max_length=122,default="")
     text3=models.CharField(max_length=122,default="")
     text4=models.CharField(max_length=122,default="")
     text5=models.CharField(max_length=122,default="")
     text6=models.CharField(max_length=122,default="")
     text7=models.CharField(max_length=122,default="")
     text8=models.CharField(max_length=122,default="")
     text9=models.CharField(max_length=122,default="")
     text10=models.CharField(max_length=122,default="")
     text11=models.CharField(max_length=122,default="")
     text12=models.CharField(max_length=122,default="")
     text13=models.CharField(max_length=122,default="")
     text14=models.CharField(max_length=122,default="")
     text15=models.CharField(max_length=122,default="")
     text16=models.CharField(max_length=122,default="")
     text17=models.CharField(max_length=122,default="")
     text18=models.CharField(max_length=122,default="")
     text19=models.CharField(max_length=122,default="")
     text20=models.CharField(max_length=122,default="")
     text21=models.CharField(max_length=122,default="")
     text22=models.CharField(max_length=122,default="")
     text23=models.CharField(max_length=122,default="")
     text24=models.CharField(max_length=122,default="")
     text25=models.CharField(max_length=122,default="")
     text26=models.CharField(max_length=122,default="")
     text27=models.CharField(max_length=122,default="")
     text28=models.CharField(max_length=122,default="")
     text29=models.CharField(max_length=122,default="")
     text30=models.CharField(max_length=122,default="")
     text31=models.CharField(max_length=122,default="")
     text32=models.CharField(max_length=122,default="")
     text33=models.CharField(max_length=122,default="")
     text34=models.CharField(max_length=122,default="")
     text35=models.CharField(max_length=122,default="")
     text36=models.CharField(max_length=122,default="")
     text37=models.CharField(max_length=122,default="")
     text38=models.CharField(max_length=122,default="")
     text39=models.CharField(max_length=122,default="")
     text40=models.CharField(max_length=122,default="")
     text41=models.CharField(max_length=122,default="")
     text42=models.CharField(max_length=122,default="")
     text43=models.CharField(max_length=122,default="")
     text44=models.CharField(max_length=122,default="")
     text45=models.CharField(max_length=122,default="")
 
class galx(models.Model):
     heading1=models.CharField(max_length=100)
     heading2=models.CharField(max_length=100)
     ima=models.ImageField(upload_to="gal/images" )
     t1=models.CharField(max_length=100)
     t11=models.CharField(max_length=100)
     t111=models.CharField(max_length=100)
     t2=models.CharField(max_length=100)
     t22=models.CharField(max_length=100)
     t222=models.CharField(max_length=100)
     t3=models.CharField(max_length=100)
     t33=models.CharField(max_length=100)
     t333=models.CharField(max_length=100)
     t4=models.CharField(max_length=100)
     t44=models.CharField(max_length=100)
     t444=models.CharField(max_length=100)
     m1=models.CharField(max_length=100)
     m11=models.CharField(max_length=100)
     m111=models.CharField(max_length=100)
     m2=models.CharField(max_length=100)
     m22=models.CharField(max_length=100)
     m222=models.CharField(max_length=100)
     m3=models.CharField(max_length=100)
     m33=models.CharField(max_length=100)
     m333=models.CharField(max_length=100)
     heading3=models.CharField(max_length=100)
     heading4=models.CharField(max_length=100)
     vid=models.FileField(upload_to="gal/images",default="")
     
     
     
     
     
        
