# Generated by Django 4.0.5 on 2022-08-05 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galaxy',
            name='image3',
            field=models.ImageField(default='', upload_to='gal/images'),
        ),
        migrations.AddField(
            model_name='galaxy',
            name='image4',
            field=models.ImageField(default='', upload_to='gal/images'),
        ),
        migrations.AddField(
            model_name='galaxy',
            name='image5',
            field=models.ImageField(default='', upload_to='gal/images'),
        ),
        migrations.AddField(
            model_name='galaxy',
            name='image6',
            field=models.ImageField(default='', upload_to='gal/images'),
        ),
        migrations.AddField(
            model_name='galaxy',
            name='image7',
            field=models.ImageField(default='', upload_to='gal/images'),
        ),
        migrations.AddField(
            model_name='galaxy',
            name='image8',
            field=models.ImageField(default='', upload_to='gal/images'),
        ),
    ]
