# Generated by Django 4.0.5 on 2022-08-05 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0002_galaxy_image3_galaxy_image4_galaxy_image5_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galaxy',
            name='image10',
            field=models.ImageField(default='', upload_to='gal/images'),
        ),
        migrations.AddField(
            model_name='galaxy',
            name='image11',
            field=models.ImageField(default='', upload_to='gal/images'),
        ),
        migrations.AddField(
            model_name='galaxy',
            name='image9',
            field=models.ImageField(default='', upload_to='gal/images'),
        ),
    ]
