# Generated by Django 4.0.5 on 2022-08-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0005_ma'),
    ]

    operations = [
        migrations.AddField(
            model_name='galaxy',
            name='text',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='galaxy',
            name='text2',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='galaxy',
            name='text3',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='galaxy',
            name='text4',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='galaxy',
            name='text5',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='galaxy',
            name='text6',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='galaxy',
            name='text7',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='galaxy',
            name='text8',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='galaxy',
            name='text9',
            field=models.CharField(default='', max_length=122),
        ),
    ]
