# Generated by Django 4.0.5 on 2022-08-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0006_galaxy_text_galaxy_text2_galaxy_text3_galaxy_text4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galaxy',
            name='text10',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='galaxy',
            name='text11',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='galaxy',
            name='text12',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='galaxy',
            name='text13',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='galaxy',
            name='text14',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='galaxy',
            name='text15',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='galaxy',
            name='text16',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='galaxy',
            name='text17',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='galaxy',
            name='text18',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='galaxy',
            name='text19',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='galaxy',
            name='text20',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='galaxy',
            name='text21',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='galaxy',
            name='text22',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='galaxy',
            name='text23',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='galaxy',
            name='text24',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='galaxy',
            name='text25',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='galaxy',
            name='text26',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='galaxy',
            name='text27',
            field=models.CharField(default='', max_length=122),
        ),
    ]
