# Generated by Django 4.0.5 on 2022-08-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0007_galaxy_text10_galaxy_text11_galaxy_text12_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galaxy',
            name='text28',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='galaxy',
            name='text29',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='galaxy',
            name='text30',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='galaxy',
            name='text31',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='galaxy',
            name='text32',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='galaxy',
            name='text33',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='galaxy',
            name='text34',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='galaxy',
            name='text35',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='galaxy',
            name='text36',
            field=models.CharField(default='', max_length=122),
        ),
    ]
