# Generated by Django 4.0.5 on 2022-08-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0008_galaxy_text28_galaxy_text29_galaxy_text30_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galaxy',
            name='text37',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='galaxy',
            name='text38',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='galaxy',
            name='text39',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='galaxy',
            name='text40',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='galaxy',
            name='text41',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='galaxy',
            name='text42',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='galaxy',
            name='text43',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='galaxy',
            name='text44',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='galaxy',
            name='text45',
            field=models.CharField(default='', max_length=122),
        ),
    ]
