# Generated by Django 4.0.5 on 2022-08-06 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0009_galaxy_text37_galaxy_text38_galaxy_text39_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ma',
            old_name='image',
            new_name='image10',
        ),
        migrations.AddField(
            model_name='ma',
            name='image11',
            field=models.ImageField(default='', upload_to='gal/images'),
        ),
        migrations.AddField(
            model_name='ma',
            name='image3',
            field=models.ImageField(default='', upload_to='gal/images'),
        ),
        migrations.AddField(
            model_name='ma',
            name='image4',
            field=models.ImageField(default='', upload_to='gal/images'),
        ),
        migrations.AddField(
            model_name='ma',
            name='image5',
            field=models.ImageField(default='', upload_to='gal/images'),
        ),
        migrations.AddField(
            model_name='ma',
            name='image6',
            field=models.ImageField(default='', upload_to='gal/images'),
        ),
        migrations.AddField(
            model_name='ma',
            name='image7',
            field=models.ImageField(default='', upload_to='gal/images'),
        ),
        migrations.AddField(
            model_name='ma',
            name='image8',
            field=models.ImageField(default='', upload_to='gal/images'),
        ),
        migrations.AddField(
            model_name='ma',
            name='image9',
            field=models.ImageField(default='', upload_to='gal/images'),
        ),
        migrations.AddField(
            model_name='ma',
            name='text',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='ma',
            name='text10',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='ma',
            name='text11',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='ma',
            name='text12',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='ma',
            name='text13',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='ma',
            name='text14',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='ma',
            name='text15',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='ma',
            name='text16',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='ma',
            name='text17',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='ma',
            name='text18',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='ma',
            name='text19',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='ma',
            name='text2',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='ma',
            name='text20',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='ma',
            name='text21',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='ma',
            name='text22',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='ma',
            name='text23',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='ma',
            name='text24',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='ma',
            name='text25',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='ma',
            name='text26',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='ma',
            name='text27',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='ma',
            name='text28',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='ma',
            name='text29',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='ma',
            name='text3',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='ma',
            name='text30',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='ma',
            name='text31',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='ma',
            name='text32',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='ma',
            name='text33',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='ma',
            name='text34',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='ma',
            name='text35',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='ma',
            name='text36',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='ma',
            name='text37',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='ma',
            name='text38',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='ma',
            name='text39',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='ma',
            name='text4',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='ma',
            name='text40',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='ma',
            name='text41',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='ma',
            name='text42',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='ma',
            name='text43',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='ma',
            name='text44',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='ma',
            name='text45',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='ma',
            name='text5',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='ma',
            name='text6',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='ma',
            name='text7',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='ma',
            name='text8',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='ma',
            name='text9',
            field=models.CharField(default='', max_length=122),
        ),
    ]
