# Generated by Django 4.0.5 on 2022-08-07 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0010_rename_image_ma_image10_ma_image11_ma_image3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galaxy',
            name='image',
            field=models.ImageField(default='', upload_to='gal/images'),
        ),
    ]
