# Generated by Django 4.0.5 on 2022-08-07 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0011_galaxy_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galaxy',
            name='image',
        ),
    ]
