# Generated by Django 4.0.5 on 2022-08-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0013_sub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub',
            name='email',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='sub',
            name='message',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='sub',
            name='name',
            field=models.CharField(max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='sub',
            name='subject',
            field=models.CharField(default='', max_length=200),
        ),
    ]
