# Generated by Django 4.0.5 on 2022-08-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0015_alter_sub_email_alter_sub_message_alter_sub_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub',
            name='email',
            field=models.CharField(blank=True, max_length=122),
        ),
        migrations.AlterField(
            model_name='sub',
            name='message',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='sub',
            name='name',
            field=models.CharField(blank=True, max_length=122),
        ),
        migrations.AlterField(
            model_name='sub',
            name='subject',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
