# Generated by Django 4.0.5 on 2022-08-07 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0016_alter_sub_email_alter_sub_message_alter_sub_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sub',
        ),
    ]
