# Generated by Django 4.0.5 on 2022-08-09 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0017_delete_sub'),
    ]

    operations = [
        migrations.CreateModel(
            name='car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image3', models.ImageField(default='', upload_to='gal/images')),
                ('image4', models.ImageField(default='', upload_to='gal/images')),
                ('image5', models.ImageField(default='', upload_to='gal/images')),
                ('image6', models.ImageField(default='', upload_to='gal/images')),
                ('image7', models.ImageField(default='', upload_to='gal/images')),
                ('image8', models.ImageField(default='', upload_to='gal/images')),
                ('image9', models.ImageField(default='', upload_to='gal/images')),
                ('image10', models.ImageField(default='', upload_to='gal/images')),
                ('image11', models.ImageField(default='', upload_to='gal/images')),
                ('text', models.CharField(default='', max_length=122)),
                ('text2', models.CharField(default='', max_length=122)),
                ('text3', models.CharField(default='', max_length=122)),
                ('text4', models.CharField(default='', max_length=122)),
                ('text5', models.CharField(default='', max_length=122)),
                ('text6', models.CharField(default='', max_length=122)),
                ('text7', models.CharField(default='', max_length=122)),
                ('text8', models.CharField(default='', max_length=122)),
                ('text9', models.CharField(default='', max_length=122)),
                ('text10', models.CharField(default='', max_length=122)),
                ('text11', models.CharField(default='', max_length=122)),
                ('text12', models.CharField(default='', max_length=122)),
                ('text13', models.CharField(default='', max_length=122)),
                ('text14', models.CharField(default='', max_length=122)),
                ('text15', models.CharField(default='', max_length=122)),
                ('text16', models.CharField(default='', max_length=122)),
                ('text17', models.CharField(default='', max_length=122)),
                ('text18', models.CharField(default='', max_length=122)),
                ('text19', models.CharField(default='', max_length=122)),
                ('text20', models.CharField(default='', max_length=122)),
                ('text21', models.CharField(default='', max_length=122)),
                ('text22', models.CharField(default='', max_length=122)),
                ('text23', models.CharField(default='', max_length=122)),
                ('text24', models.CharField(default='', max_length=122)),
                ('text25', models.CharField(default='', max_length=122)),
                ('text26', models.CharField(default='', max_length=122)),
                ('text27', models.CharField(default='', max_length=122)),
                ('text28', models.CharField(default='', max_length=122)),
                ('text29', models.CharField(default='', max_length=122)),
                ('text30', models.CharField(default='', max_length=122)),
                ('text31', models.CharField(default='', max_length=122)),
                ('text32', models.CharField(default='', max_length=122)),
                ('text33', models.CharField(default='', max_length=122)),
                ('text34', models.CharField(default='', max_length=122)),
                ('text35', models.CharField(default='', max_length=122)),
                ('text36', models.CharField(default='', max_length=122)),
                ('text37', models.CharField(default='', max_length=122)),
                ('text38', models.CharField(default='', max_length=122)),
                ('text39', models.CharField(default='', max_length=122)),
                ('text40', models.CharField(default='', max_length=122)),
                ('text41', models.CharField(default='', max_length=122)),
                ('text42', models.CharField(default='', max_length=122)),
                ('text43', models.CharField(default='', max_length=122)),
                ('text44', models.CharField(default='', max_length=122)),
                ('text45', models.CharField(default='', max_length=122)),
            ],
        ),
    ]
