# Generated by Django 4.0.5 on 2022-08-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0018_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galaxy',
            name='image10',
            field=models.FileField(default='', upload_to='gal/images'),
        ),
        migrations.AlterField(
            model_name='galaxy',
            name='image11',
            field=models.FileField(default='', upload_to='gal/images'),
        ),
        migrations.AlterField(
            model_name='galaxy',
            name='image3',
            field=models.FileField(default='', upload_to='gal/images'),
        ),
        migrations.AlterField(
            model_name='galaxy',
            name='image4',
            field=models.FileField(default='', upload_to='gal/images'),
        ),
        migrations.AlterField(
            model_name='galaxy',
            name='image5',
            field=models.FileField(default='', upload_to='gal/images'),
        ),
        migrations.AlterField(
            model_name='galaxy',
            name='image6',
            field=models.FileField(default='', upload_to='gal/images'),
        ),
        migrations.AlterField(
            model_name='galaxy',
            name='image7',
            field=models.FileField(default='', upload_to='gal/images'),
        ),
        migrations.AlterField(
            model_name='galaxy',
            name='image8',
            field=models.FileField(default='', upload_to='gal/images'),
        ),
        migrations.AlterField(
            model_name='galaxy',
            name='image9',
            field=models.FileField(default='', upload_to='gal/images'),
        ),
    ]
