# Generated by Django 4.0.5 on 2022-08-09 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0020_alter_car_image10_alter_car_image11_alter_car_image3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image10',
            field=models.ImageField(default='', upload_to='gal/images'),
        ),
        migrations.AlterField(
            model_name='car',
            name='image11',
            field=models.ImageField(default='', upload_to='gal/images'),
        ),
        migrations.AlterField(
            model_name='car',
            name='image3',
            field=models.ImageField(default='', upload_to='gal/images'),
        ),
        migrations.AlterField(
            model_name='car',
            name='image4',
            field=models.ImageField(default='', upload_to='gal/images'),
        ),
        migrations.AlterField(
            model_name='car',
            name='image5',
            field=models.ImageField(default='', upload_to='gal/images'),
        ),
        migrations.AlterField(
            model_name='car',
            name='image6',
            field=models.ImageField(default='', upload_to='gal/images'),
        ),
        migrations.AlterField(
            model_name='car',
            name='image7',
            field=models.ImageField(default='', upload_to='gal/images'),
        ),
        migrations.AlterField(
            model_name='car',
            name='image8',
            field=models.ImageField(default='', upload_to='gal/images'),
        ),
        migrations.AlterField(
            model_name='car',
            name='image9',
            field=models.ImageField(default='', upload_to='gal/images'),
        ),
    ]
