# Generated by Django 4.0.5 on 2022-08-09 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0021_alter_car_image10_alter_car_image11_alter_car_image3_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='car',
            new_name='rats',
        ),
    ]
