# Generated by Django 4.0.5 on 2022-08-14 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0023_con'),
    ]

    operations = [
        migrations.DeleteModel(
            name='con',
        ),
    ]
