# Generated by Django 4.1 on 2022-08-18 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0025_thread_chatmessage'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='thread',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='thread',
            name='first_person',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='second_person',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='Thread',
        ),
    ]
