# Generated by Django 4.1 on 2022-08-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0026_alter_thread_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='galx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=50)),
                ('heading2', models.CharField(max_length=50)),
                ('t1', models.CharField(max_length=50)),
                ('t11', models.CharField(max_length=50)),
                ('t2', models.CharField(max_length=50)),
                ('t22', models.CharField(max_length=50)),
                ('t3', models.CharField(max_length=50)),
                ('t33', models.CharField(max_length=50)),
                ('t4', models.CharField(max_length=50)),
                ('t44', models.CharField(max_length=50)),
                ('m1', models.CharField(max_length=50)),
                ('m11', models.CharField(max_length=50)),
                ('m111', models.CharField(max_length=50)),
                ('m2', models.CharField(max_length=50)),
                ('m22', models.CharField(max_length=50)),
                ('m222', models.CharField(max_length=50)),
                ('m3', models.CharField(max_length=50)),
                ('m33', models.CharField(max_length=50)),
                ('m333', models.CharField(max_length=50)),
                ('heading3', models.CharField(max_length=50)),
                ('heading4', models.CharField(max_length=50)),
            ],
        ),
    ]
