# Generated by Django 4.1 on 2022-08-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0028_galx_t111_galx_t222_galx_t333'),
    ]

    operations = [
        migrations.AddField(
            model_name='galx',
            name='t444',
            field=models.CharField(default='', max_length=50),
        ),
    ]
