# Generated by Django 4.1 on 2022-08-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0029_galx_t444'),
    ]

    operations = [
        migrations.AddField(
            model_name='galx',
            name='ims',
            field=models.ImageField(default='', upload_to='gal/images'),
        ),
    ]
