# Generated by Django 4.1 on 2022-08-22 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0030_galx_ims'),
    ]

    operations = [
        migrations.DeleteModel(
            name='galx',
        ),
    ]
