# Generated by Django 4.1 on 2022-08-22 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0031_delete_galx'),
    ]

    operations = [
        migrations.CreateModel(
            name='galx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading1', models.CharField(max_length=100)),
                ('heading2', models.CharField(max_length=100)),
                ('ima', models.ImageField(default='', upload_to='gal/images')),
                ('t1', models.CharField(max_length=100)),
                ('t11', models.CharField(max_length=100)),
                ('t111', models.CharField(max_length=100)),
                ('t2', models.CharField(max_length=100)),
                ('t22', models.CharField(max_length=100)),
                ('t222', models.CharField(max_length=100)),
                ('t3', models.CharField(max_length=100)),
                ('t33', models.CharField(max_length=100)),
                ('t333', models.CharField(max_length=100)),
                ('t4', models.CharField(max_length=100)),
                ('t44', models.CharField(max_length=100)),
                ('t444', models.CharField(max_length=100)),
                ('m1', models.CharField(max_length=100)),
                ('m11', models.CharField(max_length=100)),
                ('m111', models.CharField(max_length=100)),
                ('m2', models.CharField(max_length=100)),
                ('m22', models.CharField(max_length=100)),
                ('m222', models.CharField(max_length=100)),
                ('m3', models.CharField(max_length=100)),
                ('m33', models.CharField(max_length=100)),
                ('m333', models.CharField(max_length=100)),
                ('heading3', models.CharField(max_length=100)),
                ('heading4', models.CharField(max_length=100)),
            ],
        ),
    ]
