# Generated by Django 4.1 on 2022-08-22 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0032_galx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galx',
            name='ima',
            field=models.ImageField(upload_to='gal/images'),
        ),
    ]
