# Generated by Django 4.1 on 2022-08-22 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0033_alter_galx_ima'),
    ]

    operations = [
        migrations.AddField(
            model_name='galx',
            name='vid',
            field=models.FileField(default='', upload_to='gal/images'),
        ),
    ]
