# Generated by Django 4.1 on 2022-08-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='caption2',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='image',
            name='caption3',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='image',
            name='image2',
            field=models.ImageField(default='', upload_to='img/%y'),
        ),
        migrations.AddField(
            model_name='image',
            name='image3',
            field=models.ImageField(default='', upload_to='img/%y'),
        ),
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=models.CharField(max_length=1000),
        ),
    ]
