# Generated by Django 4.1 on 2022-08-31 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_image_caption2_image_caption3_image_image2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='caption2',
        ),
        migrations.RemoveField(
            model_name='image',
            name='caption3',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image3',
        ),
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=models.CharField(max_length=25),
        ),
    ]
